# Generated by Django 4.2.6 on 2023-10-25 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('client_status', models.BooleanField(default=False, verbose_name='Постоянный клиент')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('UAH', 'UAH'), ('BYR', 'BYR'), ('KZT', 'KZT'), ('RUB', 'RUB'), ('CNY', 'CNY'), ('INR', 'INR')], default='EUR')),
            ],
        ),
        migrations.CreateModel(
            name='OtherCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('descripsion', models.CharField(blank=True, max_length=150, verbose_name='Описание вида деятельности')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('supplyer_status', models.BooleanField(default=False, verbose_name='Надежный перевозчик')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('not ready', 'Груз не готов'), ('refused', 'Не прошли по цене'), ('allowed', 'Прошли по цене')], default='not ready')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.money')),
                ('supplyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_app.supplyer')),
            ],
        ),
    ]
