# Generated by Django 4.2.6 on 2023-10-31 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('client_status', models.BooleanField(default=False, verbose_name='Постоянный клиент')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('UAH', 'UAH'), ('BYR', 'BYR'), ('KZT', 'KZT'), ('RUB', 'RUB'), ('CNY', 'CNY'), ('INR', 'INR')], default='EUR')),
            ],
            options={
                'verbose_name': 'Деньги',
                'verbose_name_plural': 'Деньги',
            },
        ),
        migrations.CreateModel(
            name='OtherCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('descripsion', models.CharField(blank=True, max_length=150, verbose_name='Описание вида деятельности')),
            ],
            options={
                'verbose_name': 'Сторонняя организация',
                'verbose_name_plural': 'Сторонние организации',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Supplyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=35)),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=35)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления')),
                ('supplyer_status', models.BooleanField(default=False, verbose_name='Надежный перевозчик')),
            ],
            options={
                'verbose_name': 'Перевозчик',
                'verbose_name_plural': 'Перевозчики',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Sdelka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripsion', models.CharField(blank=True, max_length=150, verbose_name='Описание потребності')),
                ('transport', models.CharField(default='avto', max_length=20)),
                ('cl_price', models.CharField(default=1, max_length=20, verbose_name='цена заказчика')),
                ('cl_currency', models.CharField(default='eu', max_length=20, verbose_name='валюта заказчика')),
                ('sup_price1', models.CharField(blank=True, max_length=20, verbose_name='цена перевозчіка1')),
                ('sup_currency1', models.CharField(blank=True, max_length=20, verbose_name='валюта перевозчіка1')),
                ('sup_pometka1', models.CharField(blank=True, max_length=20, verbose_name='пометка перевозчіка1')),
                ('sup_price2', models.CharField(blank=True, max_length=20, verbose_name='цена перевозчіка2')),
                ('sup_currency2', models.CharField(blank=True, max_length=20, verbose_name='валюта перевозчіка2')),
                ('sup_pometka2', models.CharField(blank=True, max_length=20, verbose_name='пометка перевозчіка2')),
                ('common_direction', models.CharField(blank=True, max_length=20, verbose_name='общее направленіе доставкі')),
                ('common_transport', models.CharField(blank=True, max_length=20, verbose_name='транспорт іспользуемый в сделке')),
                ('profit', models.CharField(blank=True, max_length=20, verbose_name='прібыль в евро')),
                ('cl_documents', models.CharField(blank=True, max_length=20, verbose_name='документы заказчіка')),
                ('sup_documents1', models.CharField(blank=True, max_length=20, verbose_name='документы перевозчика1')),
                ('sup_documents2', models.CharField(blank=True, max_length=20, verbose_name='документы перевозчика2')),
                ('data_zagruzki_1', models.CharField(blank=True, max_length=20, verbose_name='дата выгрузки1')),
                ('data_vygruzki_1', models.CharField(blank=True, max_length=20, verbose_name='дата выгрузки1')),
                ('data_zagruzki_2', models.CharField(blank=True, max_length=20, verbose_name='дата выгрузки2')),
                ('data_vygruzki_2', models.CharField(blank=True, max_length=20, verbose_name='дата выгрузки2')),
                ('debitorks', models.BooleanField(default=False, verbose_name='подтвержение выгузки1')),
                ('debitorka2', models.BooleanField(default=False, verbose_name='подтвержение выгузки2')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='статус: текущие, закрытые, проект')),
                ('status_other', models.CharField(blank=True, max_length=20, verbose_name='статус other- новая, принята, в пути, выгружена')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='номер сделки')),
                ('client', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='crm_app.client', verbose_name='Заказчик')),
                ('supplyer1', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='Перевозчик1', to='crm_app.supplyer', verbose_name='Перевозчик1')),
                ('supplyer2', models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='Перевозчик2', to='crm_app.supplyer', verbose_name='Перевозчик2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripsion', models.CharField(blank=True, max_length=150, verbose_name='Описание потребності')),
                ('transport', models.CharField(default='avto', max_length=20)),
                ('common_direction', models.CharField(blank=True, max_length=20, verbose_name='общее направленіе доставкі')),
                ('common_transport', models.CharField(blank=True, max_length=20, verbose_name='транспорт іспользуемый в сделке')),
                ('stavka1', models.CharField(blank=True, max_length=20, verbose_name='ставка1')),
                ('comment_field1', models.CharField(blank=True, max_length=20, verbose_name='комментарій к ставке1')),
                ('stavka2', models.CharField(blank=True, max_length=20, verbose_name='ставка2')),
                ('comment_field2', models.CharField(blank=True, max_length=20, verbose_name='комментарій к ставке2')),
                ('stavka3', models.CharField(blank=True, max_length=20, verbose_name='ставка3')),
                ('comment_field3', models.CharField(blank=True, max_length=20, verbose_name='комментарій к ставке3')),
                ('stavka4', models.CharField(blank=True, max_length=20, verbose_name='ставка4')),
                ('comment_field4', models.CharField(blank=True, max_length=20, verbose_name='комментарій к ставке4')),
                ('status', models.CharField(default='новая', max_length=20, verbose_name='статус other- новая, в работе, закрыта')),
                ('result', models.CharField(default='не прошли', max_length=20, verbose_name='статус other- прошлі по цене, груз не готов, не прошлі по цене')),
                ('client', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='crm_app.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
