# Generated by Django 4.2.6 on 2023-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_10',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_3',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_4',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_5',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_6',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_7',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_8',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_vygruzki_9',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_10',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_3',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_4',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_5',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_6',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_7',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_8',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='sdelka',
            name='data_zagruzki_9',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_vygruzki_1',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_vygruzki_2',
            field=models.CharField(blank=True, null=True, verbose_name='Дата выгрузки'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_zagruzki_1',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_zagruzki_2',
            field=models.DateField(blank=True, null=True, verbose_name='Дата загрузки'),
        ),
    ]
