# Generated by Django 4.2.6 on 2023-11-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='stavka4',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stavka4', to='crm_app.supplyer', verbose_name='Перевозчик 4'),
        ),
    ]
