# Generated by Django 4.2.6 on 2023-10-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['created'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Перевозчики'},
        ),
        migrations.AlterModelOptions(
            name='money',
            options={'verbose_name': 'Деньги', 'verbose_name_plural': 'Деньги'},
        ),
        migrations.AlterModelOptions(
            name='othercompany',
            options={'ordering': ['created'], 'verbose_name': 'Сторонняя организация', 'verbose_name_plural': 'Сторонние организации'},
        ),
        migrations.AlterModelOptions(
            name='supplyer',
            options={'ordering': ['created'], 'verbose_name': 'Перевозчик', 'verbose_name_plural': 'Перевозчики'},
        ),
        migrations.AddField(
            model_name='supplyer',
            name='co_supplyers',
            field=models.ManyToManyField(blank=True, to='crm_app.supplyer'),
        ),
        migrations.DeleteModel(
            name='Stavka',
        ),
    ]
