# Generated by Django 4.2.6 on 2023-11-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='comment_field4',
            field=models.CharField(blank=True, max_length=20, verbose_name='комментарий к ставке4'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='descripsion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='result',
            field=models.CharField(default='не прошли', max_length=20, verbose_name='статус2: прошли по цене, груз не готов, не прошли по цене'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='новая', max_length=20, verbose_name='статус: новая, в работе, закрыта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_zagruzki_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='дата загрузки1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_zagruzki_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='дата загрузки2'),
        ),
    ]
