# Generated by Django 4.2.6 on 2023-12-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('Договор', 'Договор'), ('ТН', 'ТН'), ('Коносамент', 'Коносамент'), ('Дебиторка', 'Дебиторка')], default='Договор', max_length=35, verbose_name='Вид документа: '),
        ),
    ]
