# Generated by Django 4.2.6 on 2023-11-17 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdelka',
            name='cl_documents',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='документы заказчіка'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='client',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='crm_app.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='common_direction',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='общее направленіе доставкі'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='common_transport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='транспорт іспользуемый в сделке'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_vygruzki_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='дата выгрузки1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_vygruzki_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='дата выгрузки2'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_zagruzki_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='дата загрузки1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='data_zagruzki_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='дата загрузки2'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='номер сделки'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='статус: текущие, закрытые, проект'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='status_other',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='статус other- новая, принята, в пути, выгружена'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_currency1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='валюта перевозчіка1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_currency2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='валюта перевозчіка2'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_documents1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='документы перевозчика1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_documents2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='документы перевозчика2'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_pometka1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='пометка перевозчіка1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_pometka2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='пометка перевозчіка2'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_price1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='цена перевозчіка1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_price2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='цена перевозчіка2'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer1',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='Перевозчик1', to='crm_app.supplyer', verbose_name='Перевозчик1'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer2',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Перевозчик2', to='crm_app.supplyer', verbose_name='Перевозчик2'),
        ),
    ]
