# Generated by Django 4.2.6 on 2023-11-27 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdelka',
            options={'ordering': ['-time_update', '-time_create', 'number']},
        ),
        migrations.AddField(
            model_name='sdelka',
            name='comment_field10',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 10'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.client', verbose_name='Документы от заказчика'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='other_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.othercompany', verbose_name='Документы прочие'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='sdelka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.sdelka', verbose_name='Документы в сделке'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='supplyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.supplyer', verbose_name='Документы от перевозчика'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field1',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field2',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 2 '),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field3',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 3'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field4',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 4'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field5',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 5'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field6',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 6'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field7',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 7'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field8',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 8'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='comment_field9',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий Перевозчика 9'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='номер сделки'),
        ),
    ]
