# Generated by Django 4.2.6 on 2023-10-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_client_options_alter_money_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyerAdmin',
            fields=[
                ('supplyer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm_app.supplyer')),
            ],
            options={
                'abstract': False,
            },
            bases=('crm_app.supplyer',),
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['created'], 'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
    ]
