# Generated by Django 4.2.6 on 2023-11-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_sdelka_cl_documents_alter_sdelka_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdelka',
            name='sup_documents1',
        ),
        migrations.AddField(
            model_name='sdelka',
            name='sup_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='документы Перевозчика'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='cl_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='документы Заказчика'),
        ),
    ]
