# Generated by Django 4.2.6 on 2023-12-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_documents_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='other_organization',
            new_name='other_company',
        ),
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('Договор', 'Договор'), ('ТН', 'ТН'), ('Коносамент', 'Коносамент'), ('Дебиторка', 'Дебиторка')], default='Договор', max_length=35, verbose_name='Вид документа'),
        ),
    ]
