# Generated by Django 4.2.6 on 2023-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_sdelka_data_vygruzki_10_sdelka_data_vygruzki_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdelka',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='номер сделки'),
        ),
    ]
