# Generated by Django 4.2.6 on 2023-11-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_alter_sdelka_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdelka',
            name='cl_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/client', verbose_name='документы Заказчика'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='sup_documents',
            field=models.FileField(blank=True, null=True, upload_to='documents/supplyer', verbose_name='документы Перевозчика'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.client', verbose_name='Документы Заказчика')),
                ('supplyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.supplyer', verbose_name='Документы Заказчика')),
            ],
        ),
        migrations.AddField(
            model_name='sdelka',
            name='docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.documents'),
        ),
    ]
