# Generated by Django 4.2.6 on 2023-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_supplyeradmin_alter_client_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='supplyer',
            name='co_supplyers',
        ),
        migrations.DeleteModel(
            name='SupplyerAdmin',
        ),
        migrations.AddField(
            model_name='stavka',
            name='supplyers',
            field=models.ManyToManyField(related_name='Перевозчики', to='crm_app.supplyer'),
        ),
    ]
