# Generated by Django 4.2.6 on 2023-11-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_currency_quotation_price1_quotation_price2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(db_index=True, max_length=3),
        ),
    ]
