# Generated by Django 4.2.6 on 2023-11-15 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_currency_currency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'verbose_name': 'Котировка', 'verbose_name_plural': 'Котировки'},
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency10',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency10', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency4',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency4', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency5',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency5', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency6',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency6', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency7',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency7', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency8',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency8', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency9',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency9', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='price9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price1',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
