# Generated by Django 4.2.6 on 2023-11-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_alter_sdelka_cl_documents_alter_sdelka_sup_documents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='client',
            new_name='client_doc',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='file',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='supplyer',
        ),
        migrations.AddField(
            model_name='documents',
            name='name',
            field=models.CharField(choices=[('dogovor', 'Договор'), ('tn', 'ТН'), ('conosament', 'Коносамент'), ('debitorka', 'дебиторка')], default='Договор', max_length=20, verbose_name='Виды документов: '),
        ),
        migrations.AddField(
            model_name='documents',
            name='sdelka_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.sdelka', verbose_name='Документы в сделке'),
        ),
        migrations.AddField(
            model_name='documents',
            name='supplyer_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.supplyer', verbose_name='Документы Перевозчика'),
        ),
    ]
