# Generated by Django 4.2.6 on 2023-10-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_stavka_remove_supplyer_co_supplyers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stavka',
        ),
    ]
