# Generated by Django 4.2.6 on 2023-11-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_alter_quotation_options_quotation_currency10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='price1',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price10',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price2',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price3',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price4',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price5',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price6',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price7',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price8',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price9',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
