# Generated by Django 4.2.6 on 2023-12-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_sdelka_common_direction_alter_sdelka_debitorka1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField(blank=True, max_length=40, null=True, verbose_name='Дата с')),
                ('todate', models.DateField(blank=True, max_length=40, null=True, verbose_name='Дата по')),
            ],
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['time_create'], 'verbose_name': 'Котировка', 'verbose_name_plural': 'Котировки'},
        ),
        migrations.AlterModelOptions(
            name='sdelka',
            options={'ordering': ['time_create', 'number']},
        ),
        migrations.AlterField(
            model_name='quotation',
            name='comment_field2',
            field=models.CharField(blank=True, max_length=280, verbose_name='Комментарий к ставке 2'),
        ),
    ]
