# Generated by Django 4.2.6 on 2023-10-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_delete_stavka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('supplyer', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='crm_app.supplyer')),
            ],
        ),
    ]
