# Generated by Django 4.2.6 on 2023-12-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_timeperiod_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeperiod',
            options={'ordering': ['fromdate', 'todate']},
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
    ]
