# Generated by Django 4.2.6 on 2023-11-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_alter_quotation_price1_alter_quotation_price10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='direcrion')),
                ('direction_name', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направление',
            },
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='common_direction',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price10',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price2',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price3',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price4',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price5',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price6',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price7',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price8',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='price9',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='loading_country',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loading_country', to='crm_app.direction', verbose_name='Место загрузки'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='unloading_country',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unloading_country', to='crm_app.direction', verbose_name='Место выгрузки'),
        ),
    ]
