# Generated by Django 4.2.6 on 2023-11-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_transport_alter_quotation_common_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='transport',
        ),
        migrations.RemoveField(
            model_name='sdelka',
            name='transport',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='result',
            field=models.CharField(blank=True, choices=[('NOT_READY', 'Груз не готов'), ('PRICE_GOOD', 'Прошли по цене'), ('PRICE_BAD', 'Не прошли по цене')], max_length=20, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('CURRENT', 'В работе'), ('CLOSED', 'Закрыта')], default='Новая', max_length=20, verbose_name='Статус'),
        ),
    ]
