# Generated by Django 4.2.6 on 2024-01-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_alter_qfilter_options_rename_filter_qfilter_qfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdelka',
            name='currency2',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency2', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='currency3',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency3', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_2',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka2', to='crm_app.supplyer', verbose_name='Перевозчик 2'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_3',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka3', to='crm_app.supplyer', verbose_name='Перевозчик 3'),
        ),
    ]
