# Generated by Django 4.2.6 on 2024-01-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_alter_sdelka_currency2_alter_sdelka_currency3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdelka',
            name='currency10',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency10', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='currency4',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency4', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='currency5',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency5', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='currency6',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency6', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='currency7',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency7', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='currency8',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency8', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='currency9',
            field=models.ForeignKey(blank=True, max_length=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency9', to='crm_app.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_10',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka10', to='crm_app.supplyer', verbose_name='Перевозчик 10'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_4',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka4', to='crm_app.supplyer', verbose_name='Перевозчик 4'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_5',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka5', to='crm_app.supplyer', verbose_name='Перевозчик 5'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_6',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka6', to='crm_app.supplyer', verbose_name='Перевозчик 6'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_7',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka7', to='crm_app.supplyer', verbose_name='Перевозчик 7'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_8',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka8', to='crm_app.supplyer', verbose_name='Перевозчик 8'),
        ),
        migrations.AlterField(
            model_name='sdelka',
            name='supplyer_9',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stavka9', to='crm_app.supplyer', verbose_name='Перевозчик 9'),
        ),
    ]
