# Generated by Django 4.2.6 on 2024-01-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_alter_sdelka_currency10_alter_sdelka_currency4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-time_create'], 'verbose_name': 'Котировка', 'verbose_name_plural': 'Котировки'},
        ),
    ]
